ALTER TABLE TBL_USUARIOS RENAME COLUMN USUARIO_ID TO ID;
ALTER TABLE TBL_SUGESTOES RENAME COLUMN SUGESTAO_ID TO ID;
ALTER TABLE TBL_PROJETOS RENAME COLUMN PROJETO_ID TO ID;

ALTER TABLE TBL_SUGESTOES
    RENAME CONSTRAINT FK_USUARIO TO FK_SUGESTAO_USUARIO;

ALTER TABLE TBL_PROJETOS
    RENAME CONSTRAINT FK_SUGESTAO TO FK_PROJETO_SUGESTAO;